apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverctl
  labels:
    app: serverctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverctl
  template:
    metadata:
      labels:
        app: serverctl
    spec:
      containers:
      - name: serverctl
        image: docker.io/rsdias/ctl:ctl
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: serverctl
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: serverctl
  type: ClusterIP
